GET /api/departments
Host: localhost:8080
Accept: application/json

###
GET /api/departments/627f50cbfe92629d58a02606
Host: localhost:8080
Accept: application/json

###

GET /api/employees
Host: localhost:8080
Accept: application/json

###
GET /api/employees/1001
Host: localhost:8080
Accept: application/json

###

